-- SQL Server 2019 schema

CREATE TABLE [Users] (
  [Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  [Email] NVARCHAR(255) NOT NULL UNIQUE,
  [Username] NVARCHAR(64) NOT NULL UNIQUE,
  [PasswordHash] NVARCHAR(255) NOT NULL,
  [AvatarUrl] NVARCHAR(512) NULL,
  [Presence] NVARCHAR(16) NOT NULL DEFAULT 'offline',
  [CreatedAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  [UpdatedAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE [Servers] (
  [Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  [OwnerUserId] UNIQUEIDENTIFIER NOT NULL,
  [Name] NVARCHAR(100) NOT NULL,
  [Description] NVARCHAR(500) NULL,
  [CreatedAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_Servers_Owner FOREIGN KEY ([OwnerUserId]) REFERENCES [Users]([Id])
);

CREATE TABLE [ServerMemberships] (
  [ServerId] UNIQUEIDENTIFIER NOT NULL,
  [UserId] UNIQUEIDENTIFIER NOT NULL,
  [Role] NVARCHAR(24) NOT NULL DEFAULT 'member',
  [CreatedAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  PRIMARY KEY ([ServerId], [UserId]),
  CONSTRAINT FK_ServerMemberships_Server FOREIGN KEY ([ServerId]) REFERENCES [Servers]([Id]) ON DELETE CASCADE,
  CONSTRAINT FK_ServerMemberships_User FOREIGN KEY ([UserId]) REFERENCES [Users]([Id]) ON DELETE CASCADE
);

CREATE TABLE [Channels] (
  [Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  [ServerId] UNIQUEIDENTIFIER NOT NULL,
  [Type] NVARCHAR(10) NOT NULL CHECK ([Type] IN ('text', 'voice', 'dm')),
  [Name] NVARCHAR(100) NOT NULL,
  [Position] INT NOT NULL DEFAULT 0,
  [CreatedAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_Channels_Server FOREIGN KEY ([ServerId]) REFERENCES [Servers]([Id]) ON DELETE CASCADE
);

CREATE TABLE [Friends] (
  [RequesterId] UNIQUEIDENTIFIER NOT NULL,
  [AddresseeId] UNIQUEIDENTIFIER NOT NULL,
  [Status] NVARCHAR(16) NOT NULL CHECK ([Status] IN ('pending', 'accepted', 'blocked', 'rejected')),
  [CreatedAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  [UpdatedAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  PRIMARY KEY ([RequesterId], [AddresseeId]),
  CONSTRAINT FK_Friends_Requester FOREIGN KEY ([RequesterId]) REFERENCES [Users]([Id]) ON DELETE CASCADE,
  CONSTRAINT FK_Friends_Addressee FOREIGN KEY ([AddresseeId]) REFERENCES [Users]([Id]) ON DELETE CASCADE
);

CREATE TABLE [Messages] (
  [Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  [ChannelId] UNIQUEIDENTIFIER NOT NULL,
  [AuthorUserId] UNIQUEIDENTIFIER NOT NULL,
  [Content] NVARCHAR(MAX) NOT NULL,
  [EditedAt] DATETIME2 NULL,
  [DeletedAt] DATETIME2 NULL,
  [CreatedAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_Messages_Channel FOREIGN KEY ([ChannelId]) REFERENCES [Channels]([Id]) ON DELETE CASCADE,
  CONSTRAINT FK_Messages_Author FOREIGN KEY ([AuthorUserId]) REFERENCES [Users]([Id])
);

CREATE TABLE [Attachments] (
  [Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  [MessageId] UNIQUEIDENTIFIER NOT NULL,
  [StorageType] NVARCHAR(16) NOT NULL CHECK ([StorageType] IN ('local', 's3')),
  [PathOrKey] NVARCHAR(1024) NOT NULL,
  [MimeType] NVARCHAR(128) NOT NULL,
  [SizeBytes] BIGINT NOT NULL,
  [CreatedAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_Attachments_Message FOREIGN KEY ([MessageId]) REFERENCES [Messages]([Id]) ON DELETE CASCADE
);

CREATE INDEX IX_Messages_ChannelId_CreatedAt ON [Messages] ([ChannelId], [CreatedAt]);
CREATE INDEX IX_Friends_Addressee_Status ON [Friends] ([AddresseeId], [Status]);
CREATE INDEX IX_ServerMemberships_UserId ON [ServerMemberships] ([UserId]);
